apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  namespace: petclinic
  labels:
    app: vets-service
    tier: backend
    cluster: c2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
        tier: backend
        cluster: c2
    spec:
      containers:
      - name: vets-service
        image: springcommunity/spring-petclinic-vets-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: SERVER_PORT
          value: "8083"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
  namespace: petclinic
  labels:
    app: vets-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: vets-service
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: http
