apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: petclinic
data:
  # These will be updated after C2 services are deployed
  VISITS_SERVICE_URL: "http://visits-service.petclinic.svc.cluster.local:8082"
  VETS_SERVICE_URL: "http://vets-service.petclinic.svc.cluster.local:8083"
  CUSTOMERS_SERVICE_URL: "http://customers-service.petclinic.svc.cluster.local:8081"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: petclinic
  labels:
    app: api-gateway
    tier: frontend
    cluster: c1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        tier: frontend
        cluster: c1
    spec:
      containers:
      - name: api-gateway
        image: springcommunity/spring-petclinic-api-gateway:3.0.2
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        envFrom:
        - configMapRef:
            name: api-gateway-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: petclinic
  labels:
    app: api-gateway
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
