apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
  namespace: petclinic
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        # JSON logging format for Splunk ingestion
        log_format json_combined escape=json
        '{'
          '"time_local":"$time_local",'
          '"remote_addr":"$remote_addr",'
          '"request":"$request",'
          '"status": "$status",'
          '"body_bytes_sent":"$body_bytes_sent",'
          '"request_time":"$request_time",'
          '"http_referrer":"$http_referer",'
          '"http_user_agent":"$http_user_agent",'
          '"cluster":"C1",'
          '"region":"us-east-1",'
          '"app":"demo-frontend"'
        '}';

        access_log /var/log/nginx/access.log json_combined;
        error_log /var/log/nginx/error.log warn;

        server {
            listen 8080;

            # Healthy endpoint for load balancer
            location /health {
                access_log off;
                return 200 '{"status":"healthy","cluster":"C1","region":"us-east-1"}\n';
                add_header Content-Type application/json;
            }

            # Main page - shows cluster info
            location / {
                return 200 '<html><body><h1>Ciroos Demo - Cluster C1</h1><p>Region: us-east-1 (Frontend)</p><p>Status: Running</p><p>Timestamp: $time_iso8601</p></body></html>';
                add_header Content-Type text/html;
            }

            # Error injection endpoint - returns 500
            location /error {
                return 500 '{"error":"Internal Server Error","cluster":"C1","message":"Intentional error for testing"}\n';
                add_header Content-Type application/json;
            }

            # Status endpoint
            location /status {
                return 200 '{"status":"ok","cluster":"C1","uptime":"healthy","message":"Service is running"}\n';
                add_header Content-Type application/json;
            }

            # Random failure endpoint - 30% error rate
            location /random {
                set $random_fail 0;
                if ($request_id ~ [0-2]$) {
                    set $random_fail 1;
                }
                if ($random_fail = 1) {
                    return 503 '{"error":"Service Unavailable","cluster":"C1","message":"Random failure simulation"}\n';
                }
                return 200 '{"status":"ok","cluster":"C1","message":"Random endpoint - success"}\n';
                add_header Content-Type application/json;
            }

            # Info endpoint - cluster metadata
            location /info {
                return 200 '{"cluster":"C1","region":"us-east-1","tier":"frontend","app":"demo-app","version":"1.0"}\n';
                add_header Content-Type application/json;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: petclinic
  labels:
    app: demo-app
    tier: frontend
    cluster: c1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
        tier: frontend
        cluster: c1
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: demo-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: petclinic
  labels:
    app: demo-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: demo-app
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
